# Social Computing: Notebook 5

**Deadline:** 6th May 2026, 12:00

### Preliminary information:
If you copy another group’s code in Jupyter Notebooks or give someone
your code to copy, both pairs involved in this behavior will get 0
points for the Notebook. This doesn’t mean you can’t consult someone
from another pair in case you and your coding partner are stuck on a
particular part of code though! You can do it, but you need to disclose
this in the Notebook. You can write something like this in a comment
next to the part of code on which you consulted someone - “we both
couldn’t find a solution for this on our own, so we asked students X and
Y for help. They explained us how this works. Now we see the issue was
that we were doing A instead of B”. Describe what prevented you from
figuring out stuff on your own to demonstrate you understood what’s
going on, not just copied code from another pair. If you provide a
proper explanation, you won’t lose the points for this.

#### Deliverables:

1. This notebook with your code and explanations/answers
2. All files you created

- Please make sure to remove any code that you’ve used for testing and are not part of your solution, but keep the output cells.
- Rename this notebook file as described below.
- Do **not** upload the datasets (email addresses, IMDB)
- Do **not** upload your .env file with the API keys!
- Do **not** include credentials or API keys in cleartext anywhere!

**&rArr; You both have to submit your solution on OLAT, but you should submit the same files(s).**

#### How will you be graded?

You will be graded out of 100 points. Bonus tasks can earn you extra points, which you can use to make up for points lost in other notebooks.

---

Please include your names below and edit the name of the file to include your names (e.g. SC_Notebook5_Hamilton_Turing.ipynb):
- Alina Vanessa Brüllhardt
- Elias Mithanios Iskander
---

# Data Analysis and Visualization

## 1) Identifying the Country of Residence (25 points + 5 bonus points)

For this exercise you are provided with a dataset of hashed email addresses. This dataset can be found in `hashedEmailAddressesGitHubCommits.csv`, at:

https://www.dropbox.com/scl/fi/4sgxis7d161xgskgbmpji/hashedEmailAddressesGitHubCommits.csv?rlkey=gcu1tw7dpeed7bfqihv6vkfxc&dl=0.

Please make sure you can access this file.

### Exercise 1.1: Automatic Classification (8 points)

Based on the email address, we can infer different properties about the user. One example is their country of residence. For example, an email like “1315ae6229444367968a943a219f38def9a8112d@vpn-251-169.epfl.ch” will probably correspond to a user located in Switzerland, while an email of the form “59bd0a3ff43b32849b319e645d4798d8a5d1e889@philipphauer.de” will probably correspond to a user located in Germany. 

**Your tasks:**
- Write a script that automatically classifies all email addresses from the file above, based on the country of residence.
- Store the result in a pandas dataframe. This dataframe should consist of the following columns:
    1. **email:** Email address from csv file
    2. **identifier:** The part of the email address you used to determine the country
    3. **country:** Your classifier (i.e. the inferred country of residence)

In [64]:
import pandas as pd


filepath = "https://www.dropbox.com/scl/fi/4sgxis7d161xgskgbmpji/hashedEmailAddressesGitHubCommits.csv?rlkey=gcu1tw7dpeed7bfqihv6vkfxc&dl=1"
data = pd.read_csv(filepath, header = None)
data.columns = ['email']

In [65]:
#%pip install pycountry #for installing it in this env :')
import pycountry
import os

# function checks for country based on short_alpha in pycountry

def get_country_name(code):
    try:
        result = pycountry.countries.get(alpha_2=code.upper())
        return result.name if result else "unclear"
    except:
        return "unclear"
    


parts = data['email'].str.split('@', expand=True)
# random_100['username'] = parts[0]
# domain_parts = parts[1].str.split('.', expand=True)
# random_100['domain'] = domain_parts[0]

data['identifier'] = parts[1].str.split('.').str[-1]
data['country'] = data['identifier'].apply(get_country_name)


# #save to csv file
# cwd = os.getcwd()
# name = 'automatically_classified_emails.csv'
# path = cwd + '/' + name

# data.to_csv(path)

print(data.head())

                                               email identifier  country
0  9fd8de5fc2a7c2c0d469b2fff1afde4e5def37ba@georg...        com  unclear
1  229de65f28dfbfbe8eeed5e512ab772e573e891a@gmail...        com  unclear
2  869a92ca579ecfd79c8d4f27a1fc29f47d2b6b84@kitco...        com  unclear
3  f0ed5cc04491838daa1cd1ee171dabd3e0309500@cpc.a...         jp    Japan
4  1a66a945a7c848e2e3f1cd5f9692be1f16a0a484@users...        com  unclear

### Exercise 1.2: Manual Classification (7 points + 5 bonus points)

We now want to do a manual classification of 100 random samples from the list. Each member of the team should manually classify them (separately).

**Your tasks:**
1. Take a random sample of 100 entries from the dataframe your stored in exercise 1.1 and store it in a new dataframe.
    - Use a fixed seed (`random_state`) when generating the random sample.
    - Make sure to keep the original index numbers in the first column.
2. Add an empty column named "manual_classifier" to this dataframe.
3. Store this saple dataframe as a `.csv` file named `emails_manually.csv`.
4. Both team members should now separately classify the 100 addresses manually, proceeding as follows:
    1. Make your own copy of the csv file and add your name to the filename (e.g. `emails_manually_turing.csv`).
    2. Enter your manual classifiers for all addresses into the last column (manual_classifier) and store the csv.
    3. Include both csv files in your submission.

In [66]:
### Your code here
random_100 = data.sample(100, random_state=1004)
random_100['manual_classifier'] = ''


#save to csv file
cwd = os.getcwd()
name = 'emails_manually.csv'
path = cwd + '/' + name

random_100.to_csv(path)

5. Next, compare your results. Did you agree on all the 100 entries? Were you able to label all email addresses? **Please write your main conclusions below.**

You can either just compare your csv files and the labels manually, or you can solve the following bonus task first and automatically merge them into a combined dataframe, which you can then use for the comparison.

**Bonus Task (5 bonus points):**

Write a function using the code structure below, with the following requirements:
- The function takes a list of csv file paths as input and returns a dataframe with the combined data.
- The function should read all csv files into dataframes and merge them based on the common columns, i.e. the index column (that's why we kept the original indices when taking a random sample in step 1).
- The merged dataframe should consist of the following columns: 'index', 'email', 'identifier', 'country' (all of them only once!), and then one column with a distinct name for each manual classification per member/file (hint: you could determine this distinct name from the respective filename).

Call this function with your files from step 4 and store the merged dataframe as a new, combined csv file. Include this file in your submission.

**And don't forget to compare and analyse your results and write your main conclusions below!**

In [67]:
### Optional: Code structure for the bonus task

# import pandas as pd

def merge_manual_classifiers(files: list[str]) -> pd.DataFrame:
    df = pd.DataFrame()

    for file in files:
        # Your code here:
        pass # Remove this
        # ...

    return df


### Call the function with your labelled files from step 4:
combined_df = merge_manual_classifiers(
    # Change the file paths accordingly
    ["path/to/emails_manually_member1.csv", "path/to/emails_manually_member2.csv"]
)

### => Store the dataframe into a csv file and include this in your submission

# Your code here:
# ...


### Display the combined dataframe
combined_df

Empty DataFrame
Columns: []
Index: []

**Your evaluation and main conclusion:**

```
- most emails don't allow us to guess where the user is from (.com leaves it open)
- some organizations are clearly based in a country (e.g. mentions bremen in domain)
- we got the country code based ones the same, the only difference was France (435288,78e8e6391263bfc65db62cea4e3bc312c75a1cb4@VERSPIEREN.COM,COM,unclear,France,unclear) because Alina googled Verspieren and found it was a french insurance company
```

```Conclusions```
--> Our interrater agreement was super high because most email addresses are ambiguous and we looked up country codes when we didn't know them.
--> *It's hard to know the country based on the email with a simple script*

### Exercise 1.3: Evaluation (7 points)

Now, evaluate the coverage and the accuracy of your algorithm by comparing your labels with the algorithm's result. You can calculate this manually or try to write a short script that does it automatically, based on your dataframe.
1. **Coverage:** Based on the random sample, what % of the data can your algorithm classify?
2. Can you add something to your code to increase the coverage?
    - If, yes, include below your updated code.
    - How much did coverage increase?
3. **Accuracy:** Based on the _classified_ items on your list, what % did your algorithm classify _correctly?_

In [68]:
### Any code you use to evaluate the data automatically here:
def compare_raters(path_file_a, path_file_b, col_name):
    '''Compares the columns for differences and returns a percentage on how similar they are. 
    Only works if the two files have the same col_name and length!
    
    Returns a list with the percentage of overlap, tuple of absolute values(same, different) and a list of indeces where differences occured'''
    same = 0
    different = 0
    different_index = []
    file_a = pd.read_csv(path_file_a)
    col_a = list(file_a[col_name])

    file_b = pd.read_csv(path_file_b)
    col_b = list(file_b[col_name])

    for i in range(len(file_a)):
        if col_a[i].lower() == col_b[i].lower():
            same += 1
        else:
            different += 1
            different_index.append(i)

        #info about interrater differences 
    percentage = f'{int(100/len(file_a)*same)}%'
    list_with_info = [percentage, (same, different), different_index]
    return list_with_info

def compare_cols(path_file, col_a, col_b):
    '''Compares the columns for differences and returns a percentage on how similar they are. 
    Only works if the two files have the same col_name and length!
    
    Returns a list with the percentage of overlap, tuple of absolute values(same, different) and a list of indeces where differences occured'''
    same = 0
    different = 0
    different_index = []
    file_a = pd.read_csv(path_file)
    col_a = list(file_a[col_a])
    col_b = list(file_a[col_b])

    for i in range(len(file_a)):
        if col_a[i].lower() == col_b[i].lower():
            same += 1
        else:
            different += 1
            different_index.append(i)

        #info about interrater differences 
    percentage = f'{int(100/len(file_a)*same)}%'
    list_with_info = [percentage, (same, different), different_index]
    return list_with_info



def assess_coverage(dataframe, column_name):
    '''Compares the columns for differences and returns a percentage on how similar they are. 
    Only works if the two files have the same col_name and length!
    
    Returns a list with the percentage of overlap, tuple of absolute values(same, different) and a list of indeces where differences occured'''
    unclear = 0
    clear = 0
    l = list(dataframe[column_name])
    
    for item in l:
        if item.lower() == 'unclear':
            unclear += 1
        else:
            clear += 1

    #info about coverage 
    total = unclear + clear
    coverage = f'{int(100/total*clear)}%'
    return coverage



cwd = os.getcwd()
elias_path =  os.path.join(os.getcwd(), 'emails_manually_elias.csv')
alina_path = os.path.join(os.getcwd(), 'emails_manually_alina.csv')

#compared to alina
print(f''' 
Coverage = {assess_coverage(data, 'country')}

Accuracy Automatic Detection (compared to Alina) = {compare_cols(alina_path, 'country', 'manual_classifier')[0]} 
Accuracy Automatic Detection (compared to Elias) = {compare_cols(elias_path, 'country', 'manual_classifier')[0]} 

Interrater Overlap  = {compare_raters(alina_path, elias_path, 'manual_classifier')[0]}
''')

Coverage = 10%

Accuracy Automatic Detection (compared to Alina) = 96%
Accuracy Automatic Detection (compared to Elias) = 97%

Interrater Overlap  = 99%

In [69]:
### Your improved code (step 2) here:
# ...

**Your analysis and answers to all questions (coverage, coverage increase, accuracy) here:**

### Exercise 1.3: Evaluation (7 points)

1. **Coverage:** 10% of the data
2. What could be added to improve it?
    - I'm doubtful about being able to detect organizations' origins automatically (with an LLM or the right DB we could do more)
3. **Accuracy:** Based on the _classified_ items on your list, what % did your algorithm classify _correctly?_
    - When comparing it to Alina it covered 96%, compared to Elias, 97%

### Exercise 1.4: Other Characteristics (3 points)
The country of residence is not the only characteristic of the user that can be inferred from their email address. Make a short list of other characteristics that you could infer from the data.

Your answer:

```domains:
- bot / automatic reply 
- educational account
- organization
- self-hosted server

---

## 2) Processing Data and Comparing Methods (75 points + 5 bonus points)

### Preparatory task: Download the Dataset

Download the IMDB Large Movie Review Dataset from here: https://ai.stanford.edu/~amaas/data/sentiment/

### Exercise 2.1: Data Preparation (6 points)

Understand the directory structure (check out README.md file present in the downloaded folder) and write pandas code to create a dataframe with the following columns to store all the reviews:

1. **review:** The original review
2. **split_name:** Should have the values `train`, `test`, or `unsup` - determined by the folder the review is in
3. **rating:** Rating of the review
4. **label:** If the review is from `pos`/`neg` folder, `label` should be `pos`/`neg` respectively. If the label is from `unsup` folder, set the value of `label` as `na`

Every row represents a review and every column represents a property of the review. Display the dataframe to verify whether your solution looks correct.

In [3]:
import pandas as pd
import os

base_path = os.path.join(os.getcwd(), 'aclImdb')

def prepare_imdb_data(base_dir):
    data = []
    splits = ['train', 'test']
    
    for split in splits:
        split_path = os.path.join(base_dir, split)
        
        if not os.path.exists(split_path):
            continue

        for folder in os.listdir(split_path):
            folder_path = os.path.join(split_path, folder)
            
            if not os.path.isdir(folder_path):
                continue
                
            label = folder if folder in ['pos', 'neg'] else 'na'
            
            for filename in os.listdir(folder_path):
                if filename.endswith(".txt"):
                    file_full_path = os.path.join(folder_path, filename)
                    
                    try:
                        rating = filename.split('_')[1].split('.')[0]
                    except (IndexError, ValueError):
                        rating = 0

                    with open(file_full_path, 'r', encoding='utf-8') as f:
                        review_text = f.read()
                        
                    data.append({
                        'review': review_text,
                        'split_name': split,
                        'rating': int(rating),
                        'label': label
                    })
                    
    return pd.DataFrame(data)

df = prepare_imdb_data(base_path)
print(df.head())

                                              review split_name  rating label
0  Working with one of the best Shakespeare sourc...      train       4   neg
1  Well...tremors I, the original started off in ...      train       1   neg
2  Ouch! This one was a bit painful to sit throug...      train       4   neg
3  I've seen some crappy movies in my life, but t...      train       1   neg
4  "Carriers" follows the exploits of two guys an...      train       3   neg

### Exercise 2.2: Getting the Annotations (24 points)

Select 30 random reviews from the dataframe above while ensuring there are 10 reviews each for `label` = `pos`, `neg` and `na`. For all the reviews, we will use three methods: **manual** (human), **LLM-based** (LLM), and **classic NLP-based** (NLTK), to measure the _sentiment_ of the reviews.

**Your tasks:**
- For each of the 30 reviews, annotate them using each of the three methods below.
- Store the annotations in CSV files, one file for each method. In the end, you should have three CSV files, one for _human_, _LLM_, and _NLTK_, with 30 rows each (one per review).

#### Preparation Task (3 points)

- Select 30 random reviews from the dataframe above while ensuring there are 10 reviews each for `label` = `pos`, `neg` and `na`.
- Store them in a dataframe that you can use in the subsequent exercises.
- In addition, export this dataframe into a CSV file named `imdb_random_reviews.csv`. Include this file in your submission.

In [15]:
### Your code here:
subset_pos = df[df['label'] == 'pos'].sample(10, random_state=1004)
subset_neg = df[df['label'] == 'neg'].sample(10, random_state=1004)
subset_na  = df[df['label'] == 'na'].sample(10, random_state=1004)

random_reviews = pd.concat([subset_pos, subset_neg, subset_na]).reset_index(drop=True)
random_reviews.to_csv('imdb_random_reviews.csv', index=False)
random_reviews

                                               review split_name  rating label
0   Okay maybe it was because I happen to be in Ya...       test       8   pos
1   THE MERCHANT OF FOUR SEASONS was Rainer Werner...       test       9   pos
2   as a sequel,this is not a bad movie.i actually...      train       7   pos
3   I knew absolutely nothing about Chocolat befor...      train       8   pos
4   This was a great anime. True the animation is ...       test       9   pos
5   Since I am a fan of Natalie Portman, I had to ...       test       7   pos
6   I usually steer clear of TV movies because of ...      train       8   pos
7   My Santa Lucia Choir was chosen to be in this ...       test      10   pos
8   The scenes are fast-paced. the characters are ...      train      10   pos
9   This film exhibits artful cinematic techniques...      train       8   pos
10  I'm a fan of the horror movie, regardless of w...       test       3   neg
11  I can imagine why he'd want to die, after star...       test       3   neg
12  I can't believe I wasted my time with this mov...      train       2   neg
13  Steven Seagal, Mr. Personality himself, this t...      train       2   neg
14  This movie was disturbing, not because of the ...       test       3   neg
15  I'm almost embarrassed to admit to seeing CALI...       test       1   neg
16  Brilliant technology. But what good does it do...      train       3   neg
17  I was so looking forward to seeing this film t...       test       4   neg
18  As we all know Hollywood enjoys changing histo...      train       1   neg
19  I honestly can't believe what passes for enter...      train       1   neg
20  It's very rarely that I get a chance to see an...      train       0    na
21  Possibly THE most neglected movie of the 70s, ...      train       0    na
22  Okay, before I begin I should point out that t...      train       0    na
23  Those who have something invested in keeping t...      train       0    na
24  Many of the previous comments were close-minde...      train       0    na
25  When I was a kid, I played games like Freddi F...      train       0    na
26  This film was quite a pleasant surprise. I wou...      train       0    na
27  Chuck Jones as director, and that means it wil...      train       0    na
28  This film is absolutely ribbiting. The action ...      train       0    na
29  Compared to this, films like The Little Mermai...      train       0    na

#### A) Manual Labelling (7 points)

**Task:**
Create a Likert-style scale, and manually annotate the reviews using it. Justify your design choices in the cell below.

**Output:**
Store your annotations in a CSV file named `imdb_human.csv`. The file should be an extension of the `imdb_random_reviews.csv`, with an additional column **'annotation'** that contains your manual (human) annotations. Include this file in your submission.

**Briefly describe your Likert-style scale and justify your design choices:**

A 5-point scale: 1 = Very Negative, 2 = Negative, 3 = Neutral, 4 = Positive, 5 = Very Positive.

This gives enough granularity to capture degrees of sentiment without becoming ambiguous, and maps well onto VADER's compound score for normalization later.

In [16]:
### Your code here, in case you performed certain steps automatically (i.e. extending the random sample with your human annotations and storing the result in a CSV file):
annotations = [
    3, 4, 4, 1, 5, 3, 4, 2, 1, 4,  # pos (10)
    3, 3, 2, 5, 3, 4, 1, 3, 2, 3,  # neg (10)
    5, 5, 2, 1, 3, 4, 4, 5, 1, 4   # na (10)
]

random_reviews = pd.read_csv('imdb_random_reviews.csv')
random_reviews['annotation'] = annotations
random_reviews.to_csv('imdb_human.csv', index=False)

In [173]:
df_human = pd.read_csv('imdb_human.csv')

grouped = df_human.groupby(['annotation', 'label']).size().reset_index(name='frequency')

fig = px.bar(grouped, x='annotation', y='frequency', color='label',
            title='Human Annotations by Label',
            category_orders={'annotation': [1, 2, 3, 4, 5]},
            labels={'annotation': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)
fig.show()

#### B) LLM-Based Labelling (7 points)

**Task:**
Use Gemini API (from notebook 2) to automatically annotate the reviews. Please mention the scale you are using and why. It could be the Likert-style scale from above, a different Likert-style scale, a number from 0 to 10 etc. Please justify your choice and write your prompt and code in the corresponding cells below.

**Output:**
Store your annotations in a CSV file named `imdb_llm.csv`. The file should be an extension of the `imdb_random_reviews.csv`, with an additional column **'annotation'** that contains your LLM-based annotations. Include this file in your submission.

**Describe the scale and justify your choice:**

Scale Choice: 1 to 5

To be consistent with the manual rating of Elias, I chose to apply the same rating scale from 1-5 for this LLM prompt. It allows for a more granular sentiment analysis than a binary (0/1) scale, making better use of the LLM capabilities.

Prompt:
Analyze the sentiment of the following movie review. 
Assign a sentiment score using a 5-point scale: 1 = Very Negative, 2 = Negative, 3 = Neutral, 4 = Positive, 5 = Very Positive.
Output ONLY the integer score. Do not provide explanations or extra text. 
Review: ```{review_text}```

In [ ]:
%pip install -U google-genai

In [126]:
from google import genai
import pandas as pd
from dotenv import load_dotenv
import os
import time

load_dotenv()
client = genai.Client(api_key=os.getenv('GEMINI_KEY'))

df_imdb_random_reviews = pd.read_csv('imdb_random_reviews.csv')

prompt_template = (
    """Analyze the sentiment of the following movie review. 
    Assign a sentiment score using a 5-point scale: 1 = Very Negative, 2 = Negative, 3 = Neutral, 4 = Positive, 5 = Very Positive.
    Output ONLY the integer score. Do not provide explanations or extra text. 
    Review: {review_text}"""
)

annotations = []

for index, row in df_imdb_random_reviews.iterrows():
    if index >= 30: 
        break
    
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash", #is that the best free-tier one? 2.0 didn't work!
            contents=prompt_template.format(review_text=row['review'])
        )
        annotations.append(response.text.strip())
        time.sleep(8) # to stay savely under 15 requests / minute limit
        
    except Exception as e:
        if "429" in str(e): #rate limit exceeded
            print(f"Error at index {index}: {e}")
            break 
        else:
            print(f"Error at index {index}: {e}")
            annotations.append('N/A')

df_llm = df_imdb_random_reviews.copy()
remaining = 30 - len(annotations) 
annotations.extend(['N/A'] * remaining)

df_llm['label'] = annotations
df_llm.to_csv('imdb_llm_alina.csv', index=False)

Error at index 0: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, head to: https://ai.google.dev/gemini-api/docs/rate-limits. To monitor your current usage, head to: https://ai.dev/rate-limit. \n* Quota exceeded for metric: generativelanguage.googleapis.com/generate_content_free_tier_requests, limit: 20, model: gemini-2.5-flash\nPlease retry in 59.409521756s.', 'status': 'RESOURCE_EXHAUSTED', 'details': [{'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Learn more about Gemini API quotas', 'url': 'https://ai.google.dev/gemini-api/docs/rate-limits'}]}, {'@type': 'type.googleapis.com/google.rpc.QuotaFailure', 'violations': [{'quotaMetric': 'generativelanguage.googleapis.com/generate_content_free_tier_requests', 'quotaId': 'GenerateRequestsPerDayPerProjectPerModel-FreeTier', 'quotaDimensions': {'model': 'gemini-2.5-flash', 'location': 'global'}, 'quotaValue': '20'}]}, {'@type': 'type.googleapis.com/google.rpc.RetryInfo', 'retryDelay': '59s'}]}}

#### C) Classic NLP-Based Labelling (7 points)

**Task:**
Use the NLTK sentiment analyzer to get the sentiment scores and automatically annotate the reviews. Briefly explain which value you use for the annotation, what its meaning is and justify your choice.

**Output:**
Store your annotations in a CSV file named `imdb_nltk.csv`. The file should be an extension of the `imdb_random_reviews.csv`, with an additional column **'annotation'** that contains your classic NLP-based annotations. Include this file in your submission.

---

**Notes:**

- We use the [Vader](https://www.nltk.org/api/nltk.sentiment.vader.html)* sentiment analyzer for analyzing the overall sentiment of the text (positive, neutral, or negative).
- Before you can use the NLTK library, you have to download additional data (pre-trained models, corpora, and other resources); you only need to do this once.
- You can find a good example of how to install and use the Natural Language Toolkit (NLTK) and use the Vader sentiment analyzer on [this website](https://medium.com/@khalidassalafy/sentiment-analysis-with-nltk-4afbb0bf6a49).
- Be aware that we are not only interested in a binary outcome (positive/negative), but in a sentiment score! Examine what the `analyzer.polarity_scores()` function returns and which component of it you might want to use.


\* Hutto, C.J. & Gilbert, E.E. (2014). VADER: A Parsimonious Rule-based Model for Sentiment Analysis of Social Media Text. Eighth International Conference on Weblogs and Social Media (ICWSM-14). Ann Arbor, MI, June 2014.

**Explain which value you use for the annotation, what its meaning is and justify your choice:**

The compound score is a single value ranging from -1 (most negative) to +1 (most positive), aggregating VADER's positive, negative, and neutral sub-scores. It's the standard output for overall sentiment and gives a continuous scale that can be binned into the 1-5 categories later.

In [20]:
### Your code here:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

nltk.download('vader_lexicon')

sia = SentimentIntensityAnalyzer()
random_reviews = pd.read_csv('imdb_random_reviews.csv')
random_reviews['annotation'] = random_reviews['review'].apply(lambda r: sia.polarity_scores(r)['compound'])
random_reviews.to_csv('imdb_nltk.csv', index=False)
random_reviews[['label', 'annotation']]

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /Users/eliasiskander/nltk_data...

   label  annotation
0    pos      0.9936
1    pos      0.9589
2    pos      0.9692
3    pos      0.9721
4    pos      0.9761
5    pos      0.9354
6    pos      0.6369
7    pos      0.9810
8    pos      0.8908
9    pos      0.9140
10   neg     -0.9858
11   neg     -0.8459
12   neg     -0.9842
13   neg     -0.9859
14   neg     -0.9405
15   neg      0.5642
16   neg      0.9337
17   neg      0.8066
18   neg      0.6438
19   neg     -0.9858
20    na      0.8513
21    na      0.7488
22    na     -0.4306
23    na      0.9868
24    na      0.3242
25    na      0.9962
26    na      0.9663
27    na      0.9133
28    na      0.9795
29    na      0.4841

### Exercise 2.3: Visualizing the Annotations (17 points)

For the three annotators (_human, LLM-based, NLTK-based_) above, let us visualize how the annotations look like. This can help us understand how the data looks like and where there might be agreement or disagreement between the annotators.

**Your tasks:**
- For each of the three annotators, create 2 visualizations and analyze them:
    - Visualization 1: Overall distribution of categories
    - Visualization 2: Distribution of categories for each of `neg`, `pos` and `unsup` labels
    - Analyze them

#### A) Manual Annotations (5 points)

##### A1) Overall distribution of categories

Since we have some simple categorical data, we can visualize these annotations by just using a bar chart. Please use the code below to create a bar chart with distribution of categories of your Likert-style scale below. Please adjust the code according to the categories chosen by you.

In [113]:
"""
import plotly.express as px
import pandas as pd

# 1. Read the data from the corresponding .csv file into a dataframe
df = pd.read_csv("path/to/your/annotation_file.csv")

# 2. Group by annotation, then count
grouped = df.groupby('annotation').size().reset_index(name='frequency')

# 3. Create a bar plot with annotation on the x-axis and frequency on the y-axis.
#    We also define a custom order for annotation.
fig = px.bar(
    grouped,
    x='annotation',
    y='frequency',
    title='Frequency of Annotations',
    labels={'annotation': 'Annotation', 'frequency': 'Count'},
    category_orders={
        'annotation': [
            'strongly disagree',
            'disagree',
            'neither agree nor disagree',
            'agree',
            'strongly agree'
        ]
    }
)

fig.show()
"""

### Your code here:
import plotly.express as px

df_human = pd.read_csv('imdb_human.csv')
grouped = df_human.groupby('annotation').size().reset_index(name='frequency')

fig = px.bar(grouped, x='annotation', y='frequency',
            title='Human Annotation Distribution',
            category_orders={'annotation': [1, 2, 3, 4, 5]},
            labels={'annotation': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)

fig.update_xaxes(
    tickmode='array',
    tickvals=[1, 2, 3, 4, 5],
    ticktext=['1:Very Negative', '2:Negative', '3:Neutral', '4:Positive', '5:Very Positive'])

##### A2) Distribution of categories grouped by labels

Using the code above, we saw what the distribution of annotations looks like for the whole data. Let us now go into more details and check how annotations look like for each of `neg`, `pos` and `unsup` labels. Use the modified code below to add `label` in our visualization.

In [110]:
"""
import plotly.express as px
import pandas as pd

# 1. Read the data from the corresponding .csv file into a dataframe
df = pd.read_csv("path/to/your/annotation_file.csv")

# 2. Group by annotation and label, then count
grouped = df.groupby(['annotation', 'label']).size().reset_index(name='frequency')

# 3. Create a bar plot with annotation on the x-axis, frequency on the y-axis, and bars colored by label.
#    We also define a custom order for annotation.
fig = px.bar(
    grouped,
    x='annotation',
    y='frequency',
    color='label',
    title='Frequency of Annotations by Label',
    labels={'annotation': 'Annotation', 'frequency': 'Count'},
    category_orders={
        'annotation': [
            'strongly disagree',
            'disagree',
            'neither agree nor disagree',
            'agree',
            'strongly agree'
        ]
    }
)

fig.show()
"""

### Your code here:
df_human = pd.read_csv('imdb_human.csv')
grouped = df_human.groupby(['annotation', 'label']).size().reset_index(name='frequency')

fig = px.bar(grouped, x='annotation', y='frequency', color='label',
            title='Human Annotations by Label',
            category_orders={'Annotation': [1, 2, 3, 4, 5]},
            labels={'annotation': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)


fig.update_xaxes(
    tickmode='array',
    tickvals=[1, 2, 3, 4, 5],
    ticktext=['1:Very Negative', '2:Negative', '3:Neutral', '4:Positive', '5:Very Positive']
)

##### A3) Analysis

What insights do you gain from the visualizations above? What were your expectations? Were the plots similar to what you expected? Do these plots give any insights about the Likert-style scale you chose?

**You answer here:**

The distribution skews neutral to positive (3-4), with fewer extreme scores, which is pretty much expected since most reviews mix positive and negative language regardless of their label. Grouped by label, positives cluster at 4-5 and negatives at 1-3, with some overlap around 3. The unsup reviews spread across all values, which makes sense since there's no ground truth to anchor them. The 5-point scale works well here, it captures enough nuance without getting too granular. A binary scale would've lost the distinction between mildly and strongly negative/positive.

---

Now we will repeat the same exercise for LLM-based and NLTK-based annotations below. Please modify the plotting code according to your needs.

---

#### B) LLM-Based Annotations (5 points)

##### B1) Overall distribution of categories

Create a suitable visualization that shows the distribution of categories according to your chosen scale for the LLM-based annotations below.

In [109]:
import plotly.express as px

df_llm = pd.read_csv('imdb_llm.csv')
grouped = df_llm.groupby('annotation').size().reset_index(name='frequency')

fig = px.bar(grouped, x='annotation', y='frequency',
            title='LLM Annotation Distribution',
            category_orders={'annotation': [1, 2, 3, 4, 5]},
            labels={'annotation': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)

fig.update_xaxes(
    tickmode='array',
    tickvals=[1, 2, 3, 4, 5],
    ticktext=['1:Very Negative', '2:Negative', '3:Neutral', '4:Positive', '5:Very Positive']
)

##### B2) Distribution of categories grouped by labels

Repeat the visualization above, this time grouped and color-coded by the `neg`, `pos` and `unsup` labels.

In [108]:
# Your code for visualizing all annotations, grouped by labels:
df_LLM = pd.read_csv('imdb_llm.csv')
no_na = df_LLM.dropna().copy()
grouped = no_na.groupby(['annotation', 'label']).size().reset_index(name='frequency')

fig = px.bar(grouped, x='annotation', y='frequency', color='label',
            title='LLM Annotations by Label',
            category_orders={'annotation': [1, 2, 3, 4, 5]},
            labels={'annotation': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)

fig.update_xaxes(
    tickmode='array',
    tickvals=[1, 2, 3, 4, 5],
    ticktext=['1:Very Negative', '2:Negative', '3:Neutral', '4:Positive', '5:Very Positive']
)

##### B3) Analysis

What insights do you gain from the visualizations above? What were your expectations? Were the plots similar to what you expected? Do these plots give any insights about the scale you chose?

**You answer here:**
The LLM quite reliably matched the negative ones with low annotations and positive ones with positive ones.
The more neutral values are less present than in the human annotations, the model (gemini-2.0-flash) tends to sort into extremes. Again the scale works to distinguish between more neutral and more extreme sentiment. Compared to VADER, the LLM seems to better match the training data.

#### C) NLTK-Based Annotations (7 points)

##### C1) Overall distribution of categories

Create a suitable visualization that shows the distribution of categories according to the NLTK-based annotations below. (Hint: You need to find a way to display the continuous NLTK scale in a bar chart.)

In [106]:
### Your code for visualizing all annotations:
df_nltk = pd.read_csv('imdb_nltk.csv')

bins = [-1.01, -0.6, -0.2, 0.2, 0.6, 1.01]
labels = ['Very Negative', 'Negative', 'Neutral', 'Positive', 'Very Positive']
df_nltk['binned'] = pd.cut(df_nltk['annotation'], bins=bins, labels=labels)

grouped = df_nltk.groupby('binned', observed=True).size().reset_index(name='frequency')

fig = px.bar(grouped, x='binned', y='frequency',
            title='NLTK Annotation Distribution',
            category_orders={'binned': labels},
            labels={'binned': 'Sentiment', 'frequency': 'Number of Reviews'},
            width=800, height=400)
fig.show()

##### C2) Distribution of categories grouped by labels

Repeat the visualization above, this time grouped and color-coded by the `neg`, `pos` and `unsup` labels.

In [105]:
# Your code for visualizing all annotations, grouped by labels:
grouped = df_nltk.groupby(['binned', 'label'], observed=True).size().reset_index(name='frequency')

fig = px.bar(grouped, x='binned', y='frequency', color='label',
             title='NLTK Annotations by Label',
             category_orders={'binned': labels},
             labels={'binned': 'Sentiment', 'frequency': 'Number of Reviews'},
             width=800, height=400)
fig.show()

##### C3) Analysis

What insights do you gain from the visualizations above? What were your expectations? Were the plots similar to what you expected? Do these plots give any insights about the scale you chose?

**You answer here:**

NLTK skews heavily positive, with most reviews landing in the Positive or Very Positive bins. Even some negatively labeled reviews got positive compound scores, which shows VADER struggles with sarcasm and more nuanced critique. The unsup reviews are more spread out, which is expected. The continuous compound score is more granular than the 1-5 binning, so some information does get lost in the conversion. Overall VADER feels less reliable than human annotation for longer, more complex reviews.

---

### Exercise 2.4: Normalizing the Different Scales (5 points)

Since we used different scales in different types of annotations, we need to convert all of them to the same scale for comparison.

**Your tasks:**
- Convert the NLTK scores to the Likert-style scale used for human annotation.
- Do the same for the LLM-based scores, if you did not already use the same scale as for human annotation.
- Mention how you choose any thresholds and any potential pitfalls of the methodology.
- Create a new dataframe based on the random sample dataframe from the preparation task of exercise 2.2, adding three columns for the normalized annotations to it. This dataframe should contain the following columns:
    1. **review**
    2. **split_name**
    3. **rating**
    4. **label**
    5. **human:** Scores from human annotation
    6. **llm:** Normalized scores from LLM-based annotation
    7. **nltk:** Normalized scores from NLTK-based annotation

**Output:**

Store the dataframe in a CSV file named `imdb_combined.csv` and include it in your submission.

In [177]:
### Your code for scale conversions here:
#loading all datasets
df_human = pd.read_csv('imdb_human.csv')
df_llm = pd.read_csv('imdb_llm.csv')
df_nltk = pd.read_csv('imdb_nltk.csv')
df_normalized = pd.read_csv('imdb_random_reviews.csv').copy()


human_annotations = df_human['annotation'] 
llm_annotations = df_llm['annotation'] 
nltk_annotations = df_nltk['annotation'] 

normalized_human = [int(x) for x in human_annotations]
normalized_llm = [int(x) if not pd.isna(x) else 'NaN' for x in llm_annotations]
normalized_nltk = [int(round(x*2 + 3, 0)) for x in nltk_annotations]



df_normalized['human'] = normalized_human
df_normalized['llm'] = normalized_llm
df_normalized['nltk'] = normalized_nltk

df_normalized.to_csv('imdb_combined.csv')
df_normalized.head(30)

,review,split_name,rating,label,human,llm,nltk
0,Okay maybe it was because I happen to be in Ya...,test,8,pos,3,5,5
1,THE MERCHANT OF FOUR SEASONS was Rainer Werner...,test,9,pos,4,4,5
2,"as a sequel,this is not a bad movie.i actually...",train,7,pos,4,4,5
3,I knew absolutely nothing about Chocolat befor...,train,8,pos,1,4,5
4,This was a great anime. True the animation is ...,test,9,pos,5,5,5
5,"Since I am a fan of Natalie Portman, I had to ...",test,7,pos,3,5,5
6,I usually steer clear of TV movies because of ...,train,8,pos,4,NaN,4
7,My Santa Lucia Choir was chosen to be in this ...,test,10,pos,2,4,5
8,The scenes are fast-paced. the characters are ...,train,10,pos,1,NaN,5
9,This film exhibits artful cinematic techniques...,train,8,pos,4,NaN,5
10,"I'm a fan of the horror movie, regardless of w...",test,3,neg,3,2,1
11,"I can imagine why he'd want to die, after star...",test,3,neg,3,1,1
12,I can't believe I wasted my time with this mov...,train,2,neg,2,1,1
13,"Steven Seagal, Mr. Personality himself, this t...",train,2,neg,5,3,1
14,"This movie was disturbing, not because of the ...",test,3,neg,3,1,1
15,I'm almost embarrassed to admit to seeing CALI...,test,1,neg,4,1,4
16,Brilliant technology. But what good does it do...,train,3,neg,1,1,5
17,I was so looking forward to seeing this film t...,test,4,neg,3,NaN,5
18,As we all know Hollywood enjoys changing histo...,train,1,neg,2,NaN,4
19,I honestly can't believe what passes for enter...,train,1,neg,3,NaN,1
20,It's very rarely that I get a chance to see an...,train,0,na,5,5,5
21,"Possibly THE most neglected movie of the 70s, ...",train,0,na,5,NaN,4
22,"Okay, before I begin I should point out that t...",train,0,na,2,5,2
23,Those who have something invested in keeping t...,train,0,na,1,4,5
24,Many of the previous comments were close-minde...,train,0,na,3,5,4
25,"When I was a kid, I played games like Freddi F...",train,0,na,4,5,5
26,This film was quite a pleasant surprise. I wou...,train,0,na,4,NaN,5
27,"Chuck Jones as director, and that means it wil...",train,0,na,5,NaN,5
28,This film is absolutely ribbiting. The action ...,train,0,na,1,NaN,5
29,"Compared to this, films like The Little Mermai...",train,0,na,4,1,4

**You answer here:**
So our human and LLM annotations already matched the scale from 1-5, to convert the -1 to 1 scale from the nltk, we used the following logic:

y = 2x + 3 

This is because the range from -1 to 1 = 3, the range of 1 to 5 = 4. We therefore multiplied the nltk values by 2.
To shift the values to start at 1 and be neutral at 3 we added 3 (0 * 2 + 3 = 3).

⮕ We then rounded(y) to be the closest integer using round() which returns the nearest integer. We realize that rounding loses a little bit of the granularity from the float aspect, however, integers are much easier to interpret and the task required a likert-scale.

---

### Annotator Agreements

Now that we have normalized the different annotators, we can compare and evaluate them. We do this using two different statistical measures for assessing the reliability of agreement between raters: **Fleiss's kappa** and **Cohen's kappa**.

---

### Exercise 2.5: Checking Annotator Agreements using Fleiss's Kappa (8 points)

#### Task 1:
- Read about [Fleiss's Kappa](https://en.wikipedia.org/wiki/Fleiss%27_kappa) and measure the annotator agreement between the three annotators (human, LLM, NLTK). Your code should output the kappa value.
- What does the result tell you?

In [ ]:
### Your code here:

**Brief interpretation of your result:**

...

#### Task 2:
- Group the reviews by label (`pos`, `neg`, `unsup`) and check the annotator agreement using Fleiss's Kappa for these groups seperately.
- How does the result different from the previous one?

In [ ]:
### Your code here:

**Brief interpretation of your result:**

...

### Exercise 2.6: Checking Annotator Agreements using Cohen's Kappa (8 points + 5 bonus points)

#### Task 1:
- Read about [Cohen's Kappa](https://en.wikipedia.org/wiki/Cohen%27s_kappa) and use that to measure annotator agreement between two annotators at a time. Your code should output the kappa values for each pair.
- What do these results tell you?

In [ ]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

### Your code here:
def kappa_wrapper(kappa1, kappa2, kappa3):
    print('----------------------------------')

    print(f"Human vs LLM: κ = {kappa1:.3f}")
    print(f"Human vs NLTK: κ = {kappa2:.3f}")
    print(f"LLM vs NLTK: κ = {kappa3:.3f}")
    print('----------------------------------')
    

#helper to run the cohens kappas based on the subset created before
def check_cohens_kappas(y1, y2, y3):
    kappa_human_llm = cohen_kappa_score(y1, y2, weights='quadratic')
    kappa_human_nltk = cohen_kappa_score(y1, y3, weights='quadratic')
    kappa_llm_nltk   = cohen_kappa_score(y2, y3, weights='quadratic')

    kappa_wrapper(kappa_human_llm, kappa_human_nltk, kappa_llm_nltk)
    return kappa_human_llm, kappa_human_nltk, kappa_llm_nltk

#creates a subset of the different labels (neg, pos, unsup)
def check_group(group):
    subset = df_combined[df_combined['label'] == group]
    y1 = subset['human']
    y2 = subset['llm']
    y3 = subset['nltk'] 
    return check_cohens_kappas(y1, y2, y3)

#3 kappas for negative group
print(f'-----------negative-------------')
nk1, nk2, nk3 = check_group('neg')

#3 kappas for positive group
print(f'-----------positive-------------')
pk1, pk2, pk3 = check_group('pos')

#3 kappas for na / unsup group
print(f'-----------unsup-------------')
uk1, uk2, uk3 = check_group('na')

-----------negative-------------
----------------------------------
Human vs LLM: κ = 0.258
Human vs NLTK: κ = -0.286
LLM vs NLTK: κ = -0.250
----------------------------------
-----------positive-------------
----------------------------------
Human vs LLM: κ = 0.130
Human vs NLTK: κ = 0.000
LLM vs NLTK: κ = 0.000
----------------------------------
-----------unsup-------------
----------------------------------
Human vs LLM: κ = -0.079
Human vs NLTK: κ = 0.239
LLM vs NLTK: κ = 0.062
----------------------------------

**Brief interpretation of your result:**

...

#### Task 2:
- Group the reviews by label (`pos`, `neg`, `unsup`) and check the annotator agreement using Cohen's Kappa for these groups separately. Similar to the last exercise, we will check Cohen's Kappa for two annotators at a time.
- How do the results differ from the previous ones?

In [13]:
import pandas as pd
from sklearn.metrics import cohen_kappa_score

### Your code here:
def kappa_wrapper(kappa1, kappa2, kappa3):
    print('----------------------------------')

    print(f"Human vs LLM: κ = {kappa1:.3f}")
    print(f"Human vs NLTK: κ = {kappa2:.3f}")
    print(f"LLM vs NLTK: κ = {kappa3:.3f}")
    print('----------------------------------')
    

#helper to run the cohens kappas based on the subset created before
def check_cohens_kappas(y1, y2, y3):
    kappa_human_llm = cohen_kappa_score(y1, y2, weights='quadratic')
    kappa_human_nltk = cohen_kappa_score(y1, y3, weights='quadratic')
    kappa_llm_nltk   = cohen_kappa_score(y2, y3, weights='quadratic')

    kappa_wrapper(kappa_human_llm, kappa_human_nltk, kappa_llm_nltk)
    return kappa_human_llm, kappa_human_nltk, kappa_llm_nltk

#creates a subset of the different labels (neg, pos, unsup)
def check_group(group):
    subset = df_combined[df_combined['label'] == group]
    y1 = subset['human']
    y2 = subset['llm']
    y3 = subset['nltk'] 
    return check_cohens_kappas(y1, y2, y3)

#3 kappas for negative group
print(f'-----------negative-------------')
nk1, nk2, nk3 = check_group('neg')

#3 kappas for positive group
print(f'-----------positive-------------')
pk1, pk2, pk3 = check_group('pos')

#3 kappas for na / unsup group
print(f'-----------unsup-------------')
uk1, uk2, uk3 = check_group('na')

-----------negative-------------
----------------------------------
Human vs LLM: κ = 0.258
Human vs NLTK: κ = -0.286
LLM vs NLTK: κ = -0.250
----------------------------------
-----------positive-------------
----------------------------------
Human vs LLM: κ = 0.130
Human vs NLTK: κ = 0.000
LLM vs NLTK: κ = 0.000
----------------------------------
-----------unsup-------------
----------------------------------
Human vs LLM: κ = -0.079
Human vs NLTK: κ = 0.239
LLM vs NLTK: κ = 0.062
----------------------------------

**Brief interpretation of your result:**

...

#### Bonus Task (5 bonus points)
For Cohen's Kappa, you can visualize the annotator agreement between the three groups in the form of a heatmap. Use the code template below to display 4 heatmaps according to the results of task 1 (1 heatmap) and task 2 (3 heatmaps, one for each label) of exercise 2.6.

In [ ]:
"""
import matplotlib.pyplot as plt

metric_values = [[1, 2, 3], [4, 5, 6], [8, 1, 3]]
ticks = ["Human", "LLM", "NLTK"]

fig = plt.figure()
ax = fig.add_subplot()
cax = ax.matshow(metric_values)
fig.colorbar(cax)

ax.set_xticks(range(len(ticks)))
ax.set_xticklabels(ticks)
ax.set_yticks(range(len(ticks)))
ax.set_yticklabels(ticks)

plt.show()
"""

### Your code for the bonus task here:

### Exercise 2.7: Analysis (7 points)

#### Question 1

Which method out of the above (human, LLM or NLTK) do you prefer and why? Also list the pros and cons of all the three methods discussed above.

**Your answer here:**

I would argue the LLM (in this case Gemini) is the preferred method, as it has the best balance between accuracy with scalability.

Human annotation is the gold standard. It's the most nuanced, considering sarcasm, societal and cultural context, and ambiguous cases well. The downside? It's slow, time consuming/expensive, and only feasible at a small scale. At 30 reviews its okay, at 30,000 it becomes unfeasable.

NLTK/VADER is fast, free, and local, and the continuous compound score is more specific than the 1 to 5 scale. But it skews heavily positive, does not work on sarcasm and complex comments, and was unreliable when looking at our results. Several negatively labeled reviews received high compound scores because they used positive words like "brilliant technology" while still being negative overall.

LLM annotation handles context, negatives, and sarcasm pretty well, and produces a clean num output matching our scale. Especially, it correctly classified the cases VADER got wrong. The main problems, that we faced when doing this notebook as well, are API rate limits and the fact that it's kind of a black box, so specific scores are not easily explained. It's also sensitive to promping, different wording can change the results completely. The LLM gives pretty close to human quality, but adds scalability, which makes it the most practical choice for a task like this.

#### Question 2

Do you have any observations about annotator agreement/disagreement and how it changed with labels? Also mention any other observations you might have.

**Your answer here:**

The most observable pattern was that agreement differs strongly by label.

With the positive reviews, all three methods usually agreed. They ended up clustering high up on the scale. This makes sense, since positive language is easy to detect.

With negative reviews however, the disagreement was the largest. NLTK often gave higher scores to reviews that humans and the LLM correctly chosen to be negative, because VADER checks only surface-level wording rather than general intended meaning. A review calling a movie "brilliant technology but completely hollow" would score really high with VADER, but a human or LLM would clearly read it as negative. This is what caused the disproportional disagreement between NLTK and the other two methods.

For unsupervised reviews, agreement was lower across all three methods. Since they are a lot harder to diferentiate and distinguish, the methods tended to stray farther apart from one another here.
Again though, NLTK is the outlier. Human and LLM annotations have a higher likelihood of agreeing with each other compared to NLTK. VADER tends to be overly positively biased, and this causes the main disagreement within the dataset.